### ISSUE TITLE
feat: 초대장으로 팀 입장 API 구현

### ISSUE THREAD

**Issue by m1njae** [Antititi-time/T.TIME_SERVER#3]
**Feature Request**
기능 설명 : 닉네임으로 유저를 생성하고, 프로젝트 팀에 입장합니다.

**To-Do List**
- [ ] router 코드 작성
- [ ] controller 코드 작성
- [ ] service 코드 작성
- [ ] 구현 시 필요한 코드 작성
