### ISSUE TITLE
fix: 프로젝트 폴더링 수정

### ISSUE THREAD

**Issue by m1njae** [Antititi-time/T.TIME_SERVER#66]
**chore Request**
설명 : 프로젝트 폴더링을 수정합니다. 

**To-Do List**
- [ ] error폴더를 middleware 폴더에 넣습니다.
- [ ] constants 폴더를 modules 폴더에 넣습니다.
- [ ] 폴더 이름을 변경합니다.
