### ISSUE TITLE
feat: 지난 티타임 보기 조회 & auth 로직 추가

### ISSUE THREAD

**Issue by m1njae** [Antititi-time/T.TIME_SERVER#82]
**Feature Request**
기능 설명 : 지난 티타임 보기 조회합니다.

**To-Do List**
- [ ] 개인 결과 뷰 저장 API 걷어내기
- [ ] API별 auth 로직 추가
- [ ] 회원가입, 로그인 시, userId 반환
- [ ] 지난 티타임 보기 API 구현
